[build]
target = ["x86_64-unknown-linux-gnu", "arm-unknown-linux-gnueabihf"]

[target.arm-unknown-linux-gnueabihf]
linker = "rpi-tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"
