name: ci jobs for rust

on: [pull_request]

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                submodules: 'true'
            - uses: dtolnay/rust-toolchain@stable
              with:
                targets: 'arm-unknown-linux-gnueabihf'
            - run:  cargo build
    
    lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                submodules: 'true'
            - uses: dtolnay/rust-toolchain@stable
              with:
                targets: 'arm-unknown-linux-gnueabihf'
            - run:  cargo clippy

    format:
        name: format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: dtolnay/rust-toolchain@stable
            - run:  cargo fmt --all --check
